intellySell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Sales import views as Sales_views
from Sales import ajax_requests

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),
    path('ajax/',include(ajax_requests.urls)),
    path('',Sales_views.welcome),
    path('welcome',Sales_views.welcome,name='welcome'),
    path('productos/todos/<estado>',Sales_views.lista_productos,name='AllProductos'),
    path('datatables/kardex/<codigo_producto>',Sales_views.data_kardex,name='kardex'),
    path('terceros/nuevo',Sales_views.Nuevo_Tercero,name='Nuevo Tercero'),
    path('compras/nuevo',Sales_views.Nueva_Compra,name='Nueva compra'),
    path('compras/todas/<estado>',Sales_views.lista_compras,name='lista compras'),
    path('terceros/todos',Sales_views.lista_terceros,name='Lista Terceros'),
    path('compras/modificar/<proveedor>/<factura>',Sales_views.Modificar_Compra,name='Modificar Compra'),
    path('compras/transito',Sales_views.transito_compras,name='Transito compras'),
    path('ventas/pos/nuevo',Sales_views.pos,name='POS'),
    path('ventas/sesionesPOS/nueva',Sales_views.abrir_sesion_pos,name='Nueva Sesion POS'),
    path('ventas/sesionesPOS/cerrar',Sales_views.cerrar_sesion_pos,name='Cerrar Sesion POS'),
    path('ventas/tickets/todos',Sales_views.lista_tickets,name='Listado Tickets'),
    path('ventas/tickets/ver/<ticket>',Sales_views.ver_ticket,name='Ver Ticket'),
    path('ventas/tickets/devolucion/<ticket>',Sales_views.devolucion_ticket,name='Devolucion Ticket'),
    path('ventas/sesionesPOS/todas',Sales_views.lista_sesionesPOS,name='SesionesPOS'),
    path('ventas/sesionesPOS/ajustes',Sales_views.ajustes_caja,name='Ajustes Caja'),
    path('cartera/abono_cuenta',Sales_views.abono_cuenta,name='Abono a cuenta'),
    path('historyline',Sales_views.history_acciones,name='Historyline'),
    path('ventas/sesionesPOS/productos_vendidos/<sesion>',Sales_views.lista_productos_sesion),
    path('caja/ajustes/todos',Sales_views.lista_ajustes,name='Lista Ajustes'),
    path('cartera/abonos/todos',Sales_views.lista_pagos_cartera,name='Lista Abonos'),
    path('pruebas',Sales_views.lista_productos_2)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler403 = 'Sales.views.handler403'

Sales/forms.py
from django import forms
from crispy_forms import bootstrap
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
import datetime

from Sales.models import Terceros

class form_DatosProducto(forms.Form):
    Codigo = forms.CharField()
    Codigo.widget.attrs.update(id='codigo',readonly=True)
    Codigo.widget.attrs['class']='text-center'
    
    Stock = forms.IntegerField()
    Stock.widget.attrs['class']='text-center'
    Stock.widget.attrs.update(id='stock',readonly=True)
    
    Descripcion = forms.CharField()
    Descripcion.widget.attrs.update(id='descripcion')
    
    Nombre_Alterno = forms.CharField(required=False)
    Nombre_Alterno.widget.attrs.update(id='nombre_alterno')
    Nombre_Alterno.widget.attrs['class']='text-center'
    
    Codigo_Alterno = forms.CharField(required=False)
    Codigo_Alterno.widget.attrs.update(id='codigo_alterno')
    Codigo_Alterno.widget.attrs['class']='text-center'
    
    Marca = forms.CharField(required=False)
    Marca.widget.attrs.update(id='marca')
    Marca.widget.attrs['class']='text-center'
    
    Ubicacion = forms.CharField(required=False)
    Ubicacion.widget.attrs.update(id='ubicacion')
    Ubicacion.widget.attrs['class']='text-center'
    
    Precio = forms.IntegerField(min_value=0)
    Precio.widget.attrs.update(id='precio')
    Precio.widget.attrs['class']='text-center'

class form_NuevoProducto(forms.Form):
    Codigo = forms.CharField()
    Codigo.widget.attrs.update(id='codigoNuevo',readonly=True)
    Codigo.widget.attrs['class']='text-center'
    
    Descripcion = forms.CharField()
    placeholder = 'TIPO ARTICULO + MODELO MOTO + MEDIDA O TIPO + MARCA'
    Descripcion.widget.attrs.update(id='descripcionNuevo',placeholder=placeholder)
    
    Nombre_Alterno = forms.CharField(required=False)
    Nombre_Alterno.widget.attrs.update(id='nombre_alternoNuevo')
    
    Codigo_Alterno = forms.CharField(required=False)
    Codigo_Alterno.widget.attrs.update(id='codigo_alternoNuevo')
    Codigo_Alterno.widget.attrs['class']='text-center'
    
    Marca = forms.CharField(required=False)
    Marca.widget.attrs.update(id='marcaNuevo')
    Marca.widget.attrs['class']='text-center'

    Ubicacion = forms.CharField(required=False)
    Ubicacion.widget.attrs.update(id='ubicacionNuevo')
    Ubicacion.widget.attrs['class']='text-center'
    
    Precio = forms.IntegerField(min_value=0,required=False)
    Precio.widget.attrs.update(id='precioNuevo')
    Precio.widget.attrs['class']='text-center'

class form_AjustesInv(forms.Form):
    
    Codigo_ajuste = forms.CharField(label='Codigo')
    Codigo_ajuste.widget.attrs.update(id='codigoAjuste',readonly=True)
    Codigo_ajuste.widget.attrs['class']='text-center'
    
    Stock_ajuste = forms.IntegerField(label='Stock actual')
    Stock_ajuste.widget.attrs['class']='text-center'
    Stock_ajuste.widget.attrs.update(id='stockAjuste',readonly=True)
    
    Nuevo_Stock = forms.IntegerField(label='Nuevo stock',min_value=0)
    Nuevo_Stock.widget.attrs['class']='text-center'
    Nuevo_Stock.widget.attrs.update(id='nuevo_stock',readonly=True)
    
    tipos = (
        ('Debito','Debito'),
        ('Credito','Credito')
    )
    
    Tipo_ajuste=forms.ChoiceField(choices=tipos)
    Cantidad=forms.IntegerField(min_value=1)
    Cantidad.widget.attrs.update(id='cantidadAjuste')
    Cantidad.widget.attrs['class']='text-center'
    Cantidad.initial=0
    descripAjuste=forms.CharField(max_length=255,label='Descripcion')
    descripAjuste.widget.attrs.update(id='descripcionAjuste')
    
class form_Tercero(forms.Form):
    
    Identificacion = forms.CharField(max_length=255)
    Nombre = forms.CharField(max_length=255)
    Direccion = forms.CharField(max_length=255,required=False)
    Telefono_1 = forms.CharField(max_length=255,required=False,label='Celular')
    Telefono_2 = forms.CharField(max_length=255,required=False,label='Telefono')
    Tipo = forms.ChoiceField(choices=(
        ('Cliente','Cliente'),
        ('Proveedor','Proveedor')
    ))
    
class form_nuevaCompra(forms.Form):
     
    nroFactura = forms.CharField(label='Nro Factura')
    nroFactura.widget.attrs['class']='text-center'
    Fecha_Factura = forms.DateField(widget=DatePicker(
                                    options={
                                        'useCurrent': True,
                                        'collapse': False,
                                        'locale':'es',
                                        'format':'YYYY-MM-DD',
                                        
                                    },
                                    attrs={
                                        'class':'text-center',
                                        'append': 'fa fa-calendar',
                                        'icon_toggle': True,
                                    }),initial=datetime.datetime.today()) 
    
    
""" forms.DateField(label='Fecha de Nacimiento',widget=DatePicker(
                                    options={
                                        'useCurrent': True,
                                        'collapse': False,
                                        'format':'YYYY-MM-DD',
                                        
                                    },
                                    attrs={
                                        'append': 'fa fa-calendar',
                                        'icon_toggle': True,
                                    }),initial=datetime.datetime.today()) """

templates/escoger_producto.html
{%load l10n%}
<div class="modal fade" id="modalEscogerProducto" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Agregar producto a la compra</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class='table-responsive'>
                <table id='tablaEscogerProductos' class='display' style="width: 100%;">
                    <thead>
                        <tr>
                            <th class='text-center'>Codigo</th>
                            <th class='text-center'>Descripcion</th>
                            <th class='text-center'>Stock</th>
                            <th class='text-center'>Precio</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for producto in productos%}
                        <tr>
                            <td class='text-center'>{{producto.pk|unlocalize}}</td>
                            <td >{{producto.nombre}}</td>
                            <td class='text-center'>{{producto.stock}}</td>
                            <td class='text-center'>{{producto.precio}}</td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
</div>

templates/escoger_tercero.html
<div class="modal fade" id="modalEscogerTercero" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-users"></i> Escoger Tercero</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class='table-responsive'>
                <table id='tablaEscogerTercero' class='display' style="width: 100%;">
                    <thead>
                        <tr>
                            <th class='text-center'>Cedula</th>
                            <th class='text-center'>Nombre</th>
                            <th class='text-center'>Celular</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for tercero in terceros%}
                        <tr>
                            <td class='text-center'>{{tercero.pk}}</td>
                            <td >{{tercero.nombre}}</td>
                            <td class='text-center'>{{tercero.celular}}</td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
</div>

templates/lista_compras.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}Listado Terceros{%endblock%}
{%block content%}
<div class='container-lg bg-white shadow rounded'>
    <h4><i class="fas fa-pen-alt"></i> Compras {{estado}}s
        
        <button type='button' class='btn btn-outline-success float-right' style='margin-right: 1rem;'><i
                class="far fa-file-excel"></i> Exportar</button></h4>
    <br>
    <div class='table-responsive'>
        <table id='tablaTerceros' class='striped hover compact row-border' style='width: 100%;'>
            <thead>
                <tr>
                    <th class='text-center'>Factura</th>
                    <th class='text-center'>Nit</th>
                    <th class='text-center'>Proveedor</th>
                    <th class='text-center'>Fecha</th>
                    <th class='text-center'>Valor</th>
                </tr>
            </thead>
            <tbody>
                {%for compra in compras%}
                <tr>
                    <td class='text-center'>
                        {%if estado == 'Pendiente'%}
                        <div class="dropright">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{compra.nroFactura}}
                            </a>
                          
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href="#" data-toggle='modal' data-target='#modalAprobar'
                              data-prov='{{compra.proveedor_id}}' data-factura='{{compra.nroFactura}}'>Aprobar</a>
                              <a class="dropdown-item" href="/compras/modificar/{{compra.proveedor_id}}/{{compra.nroFactura}}">Modificar</a>
                            </div>
                          </div>
                        <!-- <a href='#' data-toggle='modal' data-target='#modalAprobar'
                            data-prov='{{compra.proveedor_id}}' data-factura='{{compra.nroFactura}}'>
                            {{compra.nroFactura}}
                        </a> -->
                        {%else%}
                        {{compra.nroFactura}}
                        {%endif%}
                    </td>
                    <td class='text-center'>{{compra.proveedor_id}}</td>
                    <td>{{compra.proveedor.nombre}}</td>
                    <td class='text-center'>{{compra.fecha|date:"d/m/Y"}}</td>
                    <td class='text-center'>{{compra.valor}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>
<!-- Modal -->
<form method='POST' action=''>{%csrf_token%}
    <div class="modal fade" id="modalAprobar" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Aprobar Compra</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <input type='text' name='factura' id='factura' hidden>
                <input type='text' name='proveedor' id='proveedor' hidden>
                <p><strong>¿Esta seguro que desea aprobar esta compra?</strong> Una vez aprobada no se podrá realizar ninguna modificacion.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
              <button type="submit" class="btn btn-outline-success"> Si </button>
            </div>
          </div>
        </div>
    </div>
</form>

<script>
    var tablaComprasSinAprobar=$('#tablaTerceros').DataTable({
        "order": [[ 2, "asc" ]]
    })
    $('#modalAprobar').on('show.bs.modal',function(event){
        var button = $(event.relatedTarget);
        var nit = button.data('prov')
        var fact = button.data('factura')
        $('#factura').val(fact)
        $('#proveedor').val(nit)
    });
</script>
{%endblock%}

templates/lista_history.html
{%extends 'base.html'%}
{%load l10n%}
{%load crispy_forms_tags%}
{%block title%}Listado Terceros{%endblock%}
{%block content%}
<div class='container-lg bg-white shadow rounded'>
    <h4><i class="fas fa-history"></i> Historial de Acciones
        
        <button type='button' class='btn btn-outline-success float-right' style='margin-right: 1rem;'><i
                class="far fa-file-excel"></i> Exportar</button></h4>
    <br>
    <div class='table-responsive'>
        <table id='tablaHistory' class='striped hover compact row-border' style='width: 100%;'>
            <thead>
                <tr>
                    <th class='text-center'>Id</th>
                    <th class='text-center'>Fecha</th>
                    <th class='text-center'>Usuario</th>
                    <th class='text-center'>Modulo</th>
                    <th class='text-center'>Accion</th>
                </tr>
            </thead>
            <tbody>
                {%for accion in acciones%}
                <tr>
                    <td class='text-center'>{{accion.pk|unlocalize}}</td>
                    <td class='text-center'>{{accion.fecha|date:'d/m/Y'}}</td>
                    <td class='text-center'>{{accion.usuario}}</td>
                    <td class='text-center'>{{accion.modulo}}</td>
                    <td>{{accion.accion}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>


<script>
    var tablaHistory=$('#tablaHistory').DataTable({
        "order": [[ 0, "desc" ]]
    })
</script>
{%endblock%}

templates/lista_terceros.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}Listado Terceros{%endblock%}
{%block content%}
<div class='container-lg bg-white shadow rounded'>
    <h4><i class="fas fa-users"></i> Listado de Terceros
        
        <button type='button' class='btn btn-outline-success float-right' style='margin-right: 1rem;'><i
                class="far fa-file-excel"></i> Exportar</button></h4>
    <br>
    <div class='table-responsive'>
        <table id='tablaTerceros' class='striped hover compact row-border' style='width: 100%;'>
            <thead>
                <tr>
                    <th class='text-center'>Cedula</th>
                    <th class='text-center'>Nombre</th>
                    <th class='text-center'>Celular</th>
                    <th class='text-center'>Telefono</th>
                    <th class='text-center'>Direccion</th>
                    <th class='text-center'>Tipo</th>
                </tr>
            </thead>
            <tbody>
                {%for tercero in terceros%}
                <tr>
                    <td class='text-center'>
                        <a href='#' data-toggle='modal' data-target='#modalTerceros' data-cedula='{{tercero.pk}}'
                            data-nombre='{{tercero.nombre}}' data-cel='{{producto.celular}}' data-tel='{{producto.telefono}}'
                            data-direccion='{{tercero.direccion}}' data-tipo='{{tercero.tipo.capitalize}}'>
                            {{tercero.pk}}
                        </a></td>
                    <td>{{tercero.nombre}}</td>
                    <td class='text-center'>{{tercero.celular}}</td>
                    <td class='text-center'>{{tercero.telefono}}</td>
                    <td class='text-center'>{{tercero.direccion}}</td>
                    <td class='text-center'>{{tercero.tipo.capitalize}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>
{%include 'modal_terceros.html'%}
<script>
    var tablaTerceros = $('#tablaTerceros').DataTable({
        'lengthMenu': [
                [10, 25, 50, -1],
                [10, 25, 50, 'Todos']
            ],
            "pageLength": 25,
    })
    $('#modalTerceros').on('show.bs.modal',function(event){
        var button = $(event.relatedTarget);
        var cc = button.data('cedula')
        var nombre = button.data('nombre')
        var cel = button.data('cel')
        var tel = button.data('tel')
        var dir = button.data('direccion')
        var tipo = button.data('tipo')
        $('#id_Identificacion').val(cc)
        $('#id_Tipo').val(tipo)
        $('#id_Nombre').val(nombre)
        $('#id_Direccion').val(dir)
        $('#id_Telefono_1').val(cel)
        $('#id_Telefono_2').val(tel)
    })
    $('#id_Identificacion').prop('readonly',true)
</script>
{%endblock%}

templates/modal_anularTicket.html
<div class="modal fade" id="modalAnularTicket" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-minus-circle"></i> Anular</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            ¿Estas seguro que deseas anular esta compra?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
            <input type='submit' class='btn btn-outline-success float-right' id='btnAnular' name='btnAnular' value='Si'>
        </div>
      </div>
    </div>
</div>

templates/modal_confirmar.html
<div class="modal fade" id="modalConfirmar" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-check-double"></i> Confirmar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            ¿Estas seguro que deseas grabar esta compra?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
            <button type='submit' class='btn btn-outline-success float-right' id='btnRegistrarCompra'>Si</button>
        </div>
      </div>
    </div>
</div>

templates/nueva_compra.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%load static%}

{%block title%}Nueva compra{%endblock%}

{%block content%}
<div class='container-lg bg-white rounded shadow' style='padding:1rem;padding-bottom: 3rem;'>
    <h4 class='border-bottom border-gray'><i class="fas fa-boxes"></i>
    {%if modificar%}
    Modificar compra
    {%else%}
    Registrar compra
    {%endif%}
    </h4>

    <br>
    <form method="POST" action="">{%csrf_token%}
        <div class='row'>
            <div class='col-lg-2 col-xs-12'>
                <label for='proveedorId'>Id Proveedor*</label>
                <div class='input-group'>
                    <input class='form-control' type='text' id='proveedorId' name='proveedorId' readonly required>
                    <div class='input-group-append'>
                        <button class='btn btn-outline-secondary' id='buscarProveedor' 
                        data-toggle="modal" data-target='#modalEscogerTercero'><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
            <div class='col-lg-5 col-xs-12'>
                <label for='proveedorId'>Nombre Proveedor*</label>
                <input type='text' name='nombreProveedor' id='nombreProveedor' class='form-control' readonly>
            </div>
            <div class='col-lg-2 col-xs-12'>
                {{form.nroFactura|as_crispy_field}}
            </div>
            <div class='col-lg-3 col-xs-12'>
                {{form.Fecha_Factura|as_crispy_field}}
            </div>
        </div>
        <div class='row'>
            <div class='col-lg-10 col-xs-12'>
                <p class='lead border-bottom border-gray'>Detalle Productos</p>
            </div>
            <div class='col-lg-2 col-xs-12'>
                <div class='btn-group float-right'>
                    <button type='button' class='btn btn-outline-primary ' id='btnNuevoProducto'
                    data-toggle="modal" data-target='#modalNuevoProducto'><i class="fas fa-file"></i></button>
                    <button type='button' class='btn btn-outline-success' id='btnAgregarProducto'
                    data-toggle='modal' data-target='#modalEscogerProducto'><i class="fas fa-plus-circle"></i></button>
                </div>
            </div>
        </div>
        <div class='table-responsive'>
            <table id='tablaProductosCompra' class='table table-sm table-hover'>
                <thead class='thead thead-dark'>
                    <tr>
                        <th style='width: 5%;'></th>
                        <th class='text-center' style='width: 10%;'>Codigo</th>
                        <th class='text-center' style='width: 35%;'>Descripcion</th>
                        <th class='text-center' style='width: 10%;'>Cantidad</th>
                        <th class='text-center' style='width: 10%;'>Costo</th>
                        <th class='text-center' style='width: 10%;'>Total</th>
                        <th class='text-center' style='width: 10%;'>Nuevo PVP</th>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot>
                    <tr>
                        <th colspan='3' class='text-right'>Total</th>
                        <th id='totalCantidad' class='text-center'></th>
                        <th id='totalCosto' class='text-center'></th>
                        <th id='totalTotal' class='text-center'></th>
                        <th class='text-center'></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <button type='button' class='btn btn-outline-primary float-right'
        data-toggle="modal" data-target="#modalConfirmar">Grabar</button>
        {%include 'modal_confirmar.html'%}
    </form>
</div>
{%include 'escoger_producto.html'%}
{%include 'escoger_tercero.html'%}
{%include 'nuevo_producto.html'%}
{{form.media}}
<script src='{%static "js/nueva_compra.js"%}'></script>
{%if modificar%}
<script>
    $(document).ready(function () {
    $('#proveedorId').val('{{proveedor.pk}}')
    $('#id_nroFactura').val('{{factura}}')
    $('#nombreProveedor').val('{{proveedor.nombre}}')
    var fecha = new Date('{{datos_compra.fecha|date:"c"}}')
    fecha = moment(fecha).add(1, 'days')
    $('#id_Fecha_Factura').datetimepicker('date', fecha)
    var info_producto = JSON.parse('{{detalle_compra|escapejs}}')
    for (i = 0; i < info_producto['len']; i++) {
        var codigo = info_producto[i]['producto']
        var descripcion = info_producto[i]['descripcion']
        var cantidad = info_producto[i]['cantidad']
        var costo_producto = info_producto[i]['costo']
        var costoTotal = info_producto[i]['total']
        var precio = info_producto[i]['precio']
        $('#tablaProductosCompra').append(
            $('<tr>')
            .append(
                $('<td>').append(
                    $('<button>').addClass('btn btn-outline-danger borrar').attr('type', 'button').attr('id', 'eliminilarLinea')
                    .prop('readonly', true).append('<i class="fas fa-minus-circle"></i>')
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control text-center').attr('type', 'text').attr('name', 'codigoDetalle').val(codigo).prop('readonly', true)
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control')
                    .attr('type', 'text').attr('name', 'descripcionDetalle')
                    .val(descripcion).prop('readonly', true)
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control text-center')
                    .attr('type', 'number').attr('name', 'cantidadDetalle')
                    .attr('min', '1').val(cantidad)
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control text-center')
                    .attr('type', 'number').attr('name', 'costoDetalle').attr('min', '1')
                    .val(costo_producto)
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control text-center')
                    .attr('type', 'number').attr('name', 'totalDetalle').attr('min', '1')
                    .val(costoTotal).prop('readonly', true)
                )
            )
            .append(
                $('<td>').append(
                    $('<input>').addClass('form-control text-center')
                    .attr('type', 'number').attr('name', 'nuevoPVPDetalle').attr('min', '1')
                    .val(precio)
                )
            )
        )

    }
    totalizarCompra();

    function totalizarCompra() {
        var rows = $("#tablaProductosCompra tbody").closest('tbody')
        var cantidadTotal = 0
        var costoTotal = 0
        var filas = $("#tablaProductosCompra tr").length - 2
        for (i = 0; i < filas; i++) {
            var fila = rows[0].childNodes[i]
            cantidad = parseInt($(fila.childNodes[3].childNodes[0]).val())
            costo = parseInt($(fila.childNodes[4].childNodes[0]).val())
            cantidadTotal += cantidad
            costoTotal += cantidad * costo
        }
        $('#totalCantidad').text(cantidadTotal)
        $('#totalTotal').text("$" + new Intl.NumberFormat().format(costoTotal))
    }

})
</script>
{%endif%}
{%endblock%}